# Generated by Django 5.2.17 on 2026-10-01 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=60)),
                ('country', models.CharField(default='BR', max_length=2)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=10)),
                ('air', models.CharField(choices=[('Gratuito', 'Gratuito'), ('Pago', 'Pago'), ('Não informado', 'Não informado')], default='Não informado', max_length=20)),
                ('air_confirmed_at', models.DateField(blank=True, null=True)),
                ('fingerprint', models.CharField(editable=False, max_length=64, unique=True)),
                ('external_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Falhas após abastecer', 'Falhas após abastecer'), ('Queda de rendimento', 'Queda de rendimento'), ('Dificuldade para ligar', 'Dificuldade para ligar'), ('Divergência nos valores', 'Divergência nos valores'), ('Calibrador indisponível', 'Calibrador indisponível'), ('Outro problema', 'Outro problema')], max_length=50)),
                ('description', models.TextField(max_length=1500)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado')], default='pending', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fuel.station')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Moto', 'Moto'), ('Carro', 'Carro'), ('Van', 'Van'), ('Caminhonete', 'Caminhonete'), ('Caminhão', 'Caminhão'), ('Outro', 'Outro')], max_length=20)),
                ('brand', models.CharField(max_length=80)),
                ('model', models.CharField(max_length=80)),
                ('year', models.PositiveSmallIntegerField()),
                ('capacity', models.DecimalField(decimal_places=3, max_digits=7)),
                ('fuel', models.CharField(choices=[('Gasolina comum', 'Gasolina comum'), ('Gasolina aditivada', 'Gasolina aditivada'), ('Etanol', 'Etanol'), ('Diesel S10', 'Diesel S10'), ('Diesel S500', 'Diesel S500'), ('Flex', 'Flex')], max_length=30)),
                ('primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-primary', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Refueling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('fuel', models.CharField(choices=[('Gasolina comum', 'Gasolina comum'), ('Gasolina aditivada', 'Gasolina aditivada'), ('Etanol', 'Etanol'), ('Diesel S10', 'Diesel S10'), ('Diesel S500', 'Diesel S500')], max_length=30)),
                ('price', models.DecimalField(decimal_places=3, max_digits=9)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('liters', models.DecimalField(decimal_places=3, max_digits=9)),
                ('km', models.PositiveIntegerField(blank=True, null=True)),
                ('full', models.BooleanField(default=False)),
                ('payment', models.CharField(choices=[('Pix', 'Pix'), ('Dinheiro', 'Dinheiro'), ('Débito', 'Débito'), ('Crédito', 'Crédito'), ('Aplicativo / desconto', 'Aplicativo / desconto')], max_length=30)),
                ('note', models.TextField(blank=True, max_length=1000)),
                ('share', models.BooleanField(default=True)),
                ('acknowledged', models.BooleanField(default=False)),
                ('client_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refuelings', to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refuelings', to='fuel.station')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refuelings', to='fuel.vehicle')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PriceObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel', models.CharField(choices=[('Gasolina comum', 'Gasolina comum'), ('Gasolina aditivada', 'Gasolina aditivada'), ('Etanol', 'Etanol'), ('Diesel S10', 'Diesel S10'), ('Diesel S500', 'Diesel S500')], max_length=30)),
                ('price', models.DecimalField(decimal_places=3, max_digits=9)),
                ('payment', models.CharField(choices=[('Pix', 'Pix'), ('Dinheiro', 'Dinheiro'), ('Débito', 'Débito'), ('Crédito', 'Crédito'), ('Aplicativo / desconto', 'Aplicativo / desconto')], max_length=30)),
                ('currency', models.CharField(default='BRL', max_length=3)),
                ('unit', models.CharField(default='L', max_length=10)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='observation', to='fuel.refueling')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='fuel.station')),
            ],
            options={
                'indexes': [models.Index(fields=['station', 'fuel', 'payment', 'date'], name='fuel_priceo_station_98b300_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.UniqueConstraint(condition=models.Q(('primary', True)), fields=('owner',), name='one_primary_vehicle_per_user'),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.CheckConstraint(condition=models.Q(('capacity__gt', 0)), name='vehicle_positive_capacity'),
        ),
        migrations.AddConstraint(
            model_name='refueling',
            constraint=models.UniqueConstraint(fields=('owner', 'client_id'), name='unique_user_refueling_request'),
        ),
        migrations.AddConstraint(
            model_name='refueling',
            constraint=models.CheckConstraint(condition=models.Q(('price__gt', 0), ('total__gt', 0), ('liters__gt', 0)), name='positive_refueling_values'),
        ),
    ]
