# Generated by Django 5.2.17 on 2026-10-02 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='refueling',
            name='common_payment',
            field=models.CharField(choices=[('Pix', 'Pix'), ('Dinheiro', 'Dinheiro'), ('Débito', 'Débito')], default='Pix', max_length=30),
        ),
        migrations.AddField(
            model_name='refueling',
            name='common_price',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='refueling',
            name='credit_price',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='priceobservation',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='fuel.refueling'),
        ),
        migrations.AddConstraint(
            model_name='priceobservation',
            constraint=models.UniqueConstraint(fields=('source', 'payment'), name='unique_source_payment'),
        ),
    ]
