<script setup lang="ts">
import {computed,reactive,ref,onMounted,onBeforeUnmount,nextTick,watch} from 'vue'
import {Droplet,Fuel,LayoutDashboard,History,MapPin,Car,Plus,ChevronRight,ChevronDown,ArrowUpRight,Check,CheckCheck,ShieldCheck,Info,Wallet,CalendarDays,Gauge,Bike,Search,X,SlidersHorizontal,Navigation,Wind,CheckCircle2,AlertTriangle,ReceiptText,Trash2,Star,Menu,Globe,Download,RotateCcw} from 'lucide-vue-next'
import StationMap from './StationMap.vue'
import AuthScreen from './AuthScreen.vue'
import {isDemo,currentUser,api,restoreSession,signOut,errorMessage} from './api'
import {online,installPrompt,installApp} from './pwa'
import {initialVehicles,initialStations,initialFills,type Vehicle,type Station,type Fill} from './data'
import {checkFuel,parseDecimal,normalizedName} from './domain.mjs'
type Page='home'|'fill'|'history'|'stations'|'vehicles'
const nav=[{id:'home' as Page,label:'Visão geral',icon:LayoutDashboard},{id:'fill' as Page,label:'Abastecer',icon:Fuel},{id:'history' as Page,label:'Histórico',icon:History},{id:'stations' as Page,label:'Explorar postos',icon:MapPin},{id:'vehicles' as Page,label:'Meus veículos',icon:Car}]
const page=ref<Page>('fill'),mobileMenu=ref(false)
const vehicles=ref<Vehicle[]>(isDemo?structuredClone(initialVehicles):[]),stations=ref<Station[]>(isDemo?structuredClone(initialStations):[]),fills=ref<Fill[]>(isDemo?structuredClone(initialFills):[])
const booting=ref(!isDemo),bootError=ref(''),saving=ref(false),modalSaving=ref(false)
const requestKey={signature:'',id:''}
const dateInput=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
const form=reactive({vehicle:1,station:1,date:dateInput(),fuel:'Gasolina comum',price:'6,20',total:'23,04',liters:'3,716',km:'',full:false,payment:'Pix',note:'',share:true,ack:false})
if(!isDemo)Object.assign(form,{vehicle:0,station:0,price:'',total:'',liters:''})
const selectedVehicle=computed(()=>vehicles.value.find(v=>v.id===Number(form.vehicle))!)
const selectedStation=computed(()=>stations.value.find(s=>s.id===Number(form.station)))
const calculation=computed(()=>checkFuel(form.price,form.total,form.liters))
const overCapacity=computed(()=>parseDecimal(form.liters)>(selectedVehicle.value?.capacity??Infinity))
const needsCheck=computed(()=>Boolean(calculation.value&&!calculation.value.consistent)||overCapacity.value)
const money=(n:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(n)
const num=(n:number,digits=2)=>new Intl.NumberFormat('pt-BR',{maximumFractionDigits:digits}).format(n)
const displayDate=(d:string)=>new Date(d+'T12:00:00').toLocaleDateString('pt-BR',{day:'2-digit',month:'short'})
const vehicleName=(id:number)=>{const v=vehicles.value.find(v=>v.id===id);return v?`${v.brand} ${v.model}`:'Veículo'}
const stationName=(id:number)=>stations.value.find(s=>s.id===id)?.name??'Posto'
const sortedFills=computed(()=>[...fills.value].sort((a,b)=>b.date.localeCompare(a.date)||b.id-a.id))
const latest=computed(()=>sortedFills.value.find(f=>f.vehicle===Number(form.vehicle)))
const comparison=computed(()=>{if(!latest.value||!calculation.value)return null;return parseDecimal(form.total)-parseDecimal(form.liters)*(latest.value.total/latest.value.liters)})
const totalSpend=computed(()=>fills.value.reduce((a,f)=>a+f.total,0)),totalLiters=computed(()=>fills.value.reduce((a,f)=>a+f.liters,0))
const average=computed(()=>totalLiters.value?totalSpend.value/totalLiters.value:0)
const toast=ref(''),error=ref('');let toastTimer:ReturnType<typeof setTimeout>
function notify(s:string){toast.value=s;clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.value='',6000)}
function go(p:Page){page.value=p;mobileMenu.value=false;window.scrollTo({top:0,behavior:'smooth'})}
function stationChanged(){if(selectedStation.value&&form.fuel==='Gasolina comum'&&form.payment==='Pix'&&selectedStation.value.price>0)form.price=selectedStation.value.price.toFixed(2).replace('.',',');else form.price='';form.ack=false}
function fuelChanged(){form.price='';form.ack=false}
async function saveFill(){if(saving.value)return;error.value='';const c=calculation.value;if(!c){error.value='Informe preço, total e litros maiores que zero.';return}if(!selectedStation.value||!selectedVehicle.value){error.value='Selecione o veículo e o posto.';return}if(!form.date||form.date>dateInput()){error.value='Escolha a data de hoje ou uma data anterior.';return}if(needsCheck.value&&!form.ack){error.value='Confira os valores e confirme a revisão antes de salvar.';return}
 const km=form.km.trim()?parseDecimal(form.km):null;if(km!==null&&(!Number.isFinite(km)||!Number.isInteger(km)||km<0)){error.value='Confira a quilometragem.';return}
 const record:Fill={id:Date.now(),vehicle:Number(form.vehicle),station:Number(form.station),date:form.date,fuel:form.fuel,price:parseDecimal(form.price),total:parseDecimal(form.total),liters:parseDecimal(form.liters),km,full:form.full,payment:form.payment,note:form.note.trim()};if(!isDemo){saving.value=true;try{const payload={...record,id:undefined,price:form.price.replace(',','.'),total:form.total.replace(',','.'),liters:form.liters.replace(',','.'),share:form.share,acknowledged:form.ack};const signature=JSON.stringify(payload);if(signature!==requestKey.signature){requestKey.signature=signature;requestKey.id=crypto.randomUUID()}const result=await api('refuelings/','POST',{...payload,client_id:requestKey.id});record.id=result.id;requestKey.signature='';}catch(e){error.value=errorMessage(e);return}finally{saving.value=false}}
 if(!fills.value.some(f=>f.id===record.id))fills.value.unshift(record);if(isDemo&&form.share&&form.fuel==='Gasolina comum'&&form.payment==='Pix'&&form.date>=selectedStation.value.updated){selectedStation.value.price=record.price;selectedStation.value.updated=form.date}form.total='';form.liters='';form.km='';form.note='';form.ack=false;notify(isDemo?'Abastecimento salvo nesta sessão de demonstração.':'Abastecimento salvo na sua conta.');go('history');if(!isDemo)refreshStations().catch(()=>{})}
function resetForm(){Object.assign(form,{vehicle:vehicles.value.find(v=>v.primary)?.id??vehicles.value[0]?.id??0,station:stations.value[0]?.id??0,date:dateInput(),fuel:'Gasolina comum',price:isDemo?'6,20':'',total:'',liters:'',km:'',full:false,payment:'Pix',note:'',share:true,ack:false});error.value=''}
const historyQuery=ref(''),historyVehicle=ref('all'),historyMonth=ref('all')
const historyMonths=computed(()=>[...new Set(fills.value.map(f=>f.date.slice(0,7)))].sort().reverse())
const filteredFills=computed(()=>sortedFills.value.filter(f=>(historyVehicle.value==='all'||f.vehicle===Number(historyVehicle.value))&&(historyMonth.value==='all'||f.date.startsWith(historyMonth.value))&&normalizedName(stationName(f.station)+' '+vehicleName(f.vehicle)+' '+f.fuel).includes(normalizedName(historyQuery.value))))
const stationQuery=ref(''),region=ref('São Luís'),sort=ref('cheap'),onlyAir=ref(false),mapSelected=ref(1)
const rankedStations=computed(()=>stations.value.filter(s=>normalizedName(s.name+' '+s.address).includes(normalizedName(stationQuery.value))&&(region.value==='Brasil'||(region.value==='Maranhão'?s.state.toUpperCase()==='MA':normalizedName(s.city)==='sao luis'))&&(!onlyAir.value||s.air==='Gratuito')).sort((a,b)=>sort.value==='cheap'?a.price-b.price:b.price-a.price))
const stationDetail=computed(()=>stations.value.find(s=>s.id===mapSelected.value))
function fillAt(s:Station){form.station=s.id;form.fuel='Gasolina comum';form.payment='Pix';stationChanged();go('fill')}
const modal=ref<HTMLDialogElement|null>(null),modalType=ref<'vehicle'|'station'|'fillDetail'|'report'>('vehicle'),modalError=ref(''),editingId=ref<number|null>(null),detailFill=ref<Fill|null>(null)
const vehicleDraft=reactive({type:'Moto',brand:'',model:'',year:2023,capacity:'',fuel:'Gasolina comum',primary:false})
const stationDraft=reactive({name:'',address:'',city:'São Luís',state:'MA',lat:'',lng:'',air:'Não informado'})
const reportDraft=reactive({type:'Falhas após abastecer',description:'',date:dateInput()}),reports=ref<{station:number,type:string}[]>([])
function openModal(type:typeof modalType.value){modalType.value=type;modalError.value='';nextTick(()=>modal.value?.showModal())}
function closeModal(){modal.value?.close()}
function newVehicle(){editingId.value=null;Object.assign(vehicleDraft,{type:'Moto',brand:'',model:'',year:2023,capacity:'',fuel:'Gasolina comum',primary:false});openModal('vehicle')}
function editVehicle(v:Vehicle){editingId.value=v.id;Object.assign(vehicleDraft,{...v,capacity:String(v.capacity).replace('.',',')});openModal('vehicle')}
async function saveVehicle(){if(modalSaving.value)return;const capacity=parseDecimal(vehicleDraft.capacity);if(!vehicleDraft.brand.trim()||!vehicleDraft.model.trim()||!Number.isFinite(capacity)||capacity<=0){modalError.value='Preencha marca, modelo e capacidade válida do tanque.';return}if(vehicleDraft.year<1900||vehicleDraft.year>new Date().getFullYear()+1){modalError.value='Confira o ano do veículo.';return}const data:Vehicle={id:editingId.value??Date.now(),type:vehicleDraft.type,brand:vehicleDraft.brand.trim(),model:vehicleDraft.model.trim(),year:Number(vehicleDraft.year),capacity,fuel:vehicleDraft.fuel,primary:vehicleDraft.primary};if(!isDemo){modalSaving.value=true;try{const result=await api(editingId.value?`vehicles/${editingId.value}/`:'vehicles/',editingId.value?'PATCH':'POST',data);data.id=result.id;data.capacity=Number(result.capacity);data.primary=result.primary;}catch(e){modalError.value=errorMessage(e);return}finally{modalSaving.value=false}}if(data.primary)vehicles.value.forEach(v=>v.primary=false);if(editingId.value){const i=vehicles.value.findIndex(v=>v.id===editingId.value);vehicles.value[i]=data}else{vehicles.value.push(data);form.vehicle=data.id}if(!vehicles.value.some(v=>v.primary))vehicles.value[0].primary=true;closeModal();notify(isDemo?'Veículo salvo nesta sessão.':'Veículo salvo na sua conta.')}
function newStation(){Object.assign(stationDraft,{name:'',address:'',city:'São Luís',state:'MA',lat:'',lng:'',air:'Não informado'});openModal('station')}
async function saveStation(){if(modalSaving.value)return;if(!stationDraft.name.trim()||!stationDraft.address.trim()||!stationDraft.city.trim()||!stationDraft.state.trim()){modalError.value='Preencha nome, endereço, cidade e estado.';return}const duplicate=stations.value.find(s=>normalizedName(s.name)===normalizedName(stationDraft.name)&&normalizedName(s.city)===normalizedName(stationDraft.city)&&normalizedName(s.address)===normalizedName(stationDraft.address));if(duplicate){form.station=duplicate.id;closeModal();stationChanged();notify('Este posto já existe. Selecionamos o cadastro disponível.');return}const lat=Number(stationDraft.lat.replace(',','.')),lng=Number(stationDraft.lng.replace(',','.'));if(!stationDraft.lat||!stationDraft.lng||!Number.isFinite(lat)||!Number.isFinite(lng)||Math.abs(lat)>90||Math.abs(lng)>180){modalError.value='Informe coordenadas válidas ou use sua localização.';return}const s:Station={id:Date.now(),name:stationDraft.name.trim(),address:stationDraft.address.trim(),city:stationDraft.city.trim(),state:stationDraft.state.toUpperCase(),lat,lng,price:0,air:stationDraft.air as Station['air'],updated:dateInput()};if(!isDemo){modalSaving.value=true;try{const result=await api('stations/','POST',{...s,country:'BR'});s.id=result.id;s.price=Number(result.price??0);s.updated=result.updated??'';}catch(e){modalError.value=errorMessage(e);return}finally{modalSaving.value=false}}if(!stations.value.some(item=>item.id===s.id))stations.value.push(s);form.station=s.id;form.price='';closeModal();notify(isDemo?'Posto adicionado apenas nesta demonstração.':'Posto cadastrado. Você já pode registrar o abastecimento.')}
const locating=ref(false)
function locate(){modalError.value='';if(!navigator.geolocation){modalError.value='Localização indisponível. Preencha as coordenadas manualmente.';return}locating.value=true;navigator.geolocation.getCurrentPosition(p=>{stationDraft.lat=p.coords.latitude.toFixed(6);stationDraft.lng=p.coords.longitude.toFixed(6);locating.value=false},()=>{modalError.value='Não foi possível acessar a localização. Você pode preencher os campos manualmente.';locating.value=false},{enableHighAccuracy:true,timeout:10000})}
function openFill(f:Fill){detailFill.value=f;openModal('fillDetail')}
async function submitReport(){if(modalSaving.value)return;if(reportDraft.description.trim().length<15){modalError.value='Descreva o ocorrido em pelo menos 15 caracteres.';return}if(!isDemo){modalSaving.value=true;try{await api('reports/','POST',{station:mapSelected.value,...reportDraft})}catch(e){modalError.value=errorMessage(e);return}finally{modalSaving.value=false}}reports.value.push({station:mapSelected.value,type:reportDraft.type});closeModal();reportDraft.description='';notify(isDemo?'Relato simulado: aguardando moderação. Nenhuma denúncia foi publicada.':'Relato enviado para moderação. Não foi publicado automaticamente.')}
function exportHistory(){const csv='\uFEFFData;Veículo;Posto;Combustível;Preço por litro;Total;Litros\n'+filteredFills.value.map(f=>[f.date,vehicleName(f.vehicle),stationName(f.station),f.fuel,f.price.toFixed(2).replace('.',','),f.total.toFixed(2).replace('.',','),f.liters.toFixed(3).replace('.',',')].map(x=>'"'+(/^[=+@\-\t\r]/.test(String(x))?"'":'')+String(x).replace(/"/g,'""')+'"').join(';')).join('\n');const u=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8;'}));const a=document.createElement('a');a.href=u;a.download=isDemo?'meu-combustivel-demonstracao.csv':'meu-combustivel-historico.csv';a.click();URL.revokeObjectURL(u)}
const pricedStations=computed(()=>rankedStations.value.filter(s=>s.price>0))
const cheapest=computed(()=>[...stations.value].filter(s=>s.price>0).sort((a,b)=>a.price-b.price)[0])
function mapStation(s:any):Station{return {...s,lat:Number(s.lat),lng:Number(s.lng),price:Number(s.price??0),updated:s.updated??''}}
async function refreshStations(){stations.value=(await api<any[]>('stations/')).map(mapStation)}
async function loadAccount(){const [vs,ss,fs]=await Promise.all([api<any[]>('vehicles/'),api<any[]>('stations/'),api<any[]>('refuelings/')]);vehicles.value=vs.map(v=>({...v,capacity:Number(v.capacity)}));stations.value=ss.map(mapStation);fills.value=fs.map(f=>({...f,price:Number(f.price),total:Number(f.total),liters:Number(f.liters)}));resetForm();mapSelected.value=stations.value[0]?.id??0;if(!vehicles.value.length)page.value='vehicles'}
async function startAccount(){booting.value=true;bootError.value='';try{await restoreSession();if(currentUser.value)await loadAccount()}catch(e){bootError.value=errorMessage(e)}finally{booting.value=false}}
async function enterAccount(){booting.value=true;bootError.value='';try{await loadAccount()}catch(e){bootError.value=errorMessage(e)}finally{booting.value=false}}
function clearPrivateState(){vehicles.value=[];fills.value=[];stations.value=[];reports.value=[];detailFill.value=null;closeModal();resetForm();Object.assign(vehicleDraft,{brand:'',model:'',capacity:''});reportDraft.description='';requestKey.signature='';requestKey.id='';page.value='fill'}
async function logoutAccount(){try{await signOut();clearPrivateState()}catch(e){notify(errorMessage(e))}}
watch(pricedStations,(list)=>{if(!list.some(s=>s.id===mapSelected.value))mapSelected.value=list[0]?.id??0})
onMounted(()=>{if(!isDemo){startAccount();window.addEventListener('session-expired',clearPrivateState)}})
onBeforeUnmount(()=>window.removeEventListener('session-expired',clearPrivateState))
const webmcpLifecycle=new AbortController()
onMounted(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;Promise.resolve(context.registerTool({name:'conferir_abastecimento',title:'Conferir abastecimento',description:'Calcula a consistência entre preço por litro, total e litros. Não salva dados.',inputSchema:{type:'object',properties:{preco:{type:'number',exclusiveMinimum:0},total:{type:'number',exclusiveMinimum:0},litros:{type:'number',exclusiveMinimum:0}},required:['preco','total','litros'],additionalProperties:false},annotations:{readOnlyHint:true},execute(input:any){if(!input||typeof input.preco!=='number'||typeof input.total!=='number'||typeof input.litros!=='number')throw new Error('Valores numéricos são obrigatórios.');const r=checkFuel(input.preco,input.total,input.litros);if(!r)throw new Error('Os valores devem ser positivos e finitos.');return r}},{signal:webmcpLifecycle.signal})).catch(()=>{})})
onBeforeUnmount(()=>{webmcpLifecycle.abort();clearTimeout(toastTimer)})
</script>

<template>
 <div v-if="booting" class="boot-screen" role="status"><Droplet :size="36"/><h1>Meu Combustível</h1><p>Conectando à sua conta…</p></div>
 <div v-else-if="bootError" class="boot-screen"><AlertTriangle :size="36"/><h1>Não foi possível conectar</h1><p>{{bootError}}</p><button class="primary-button" @click="startAccount">Tentar novamente</button></div>
 <AuthScreen v-else-if="!isDemo&&!currentUser" @authenticated="enterAccount"/>
 <div v-else class="app-shell">
 <aside class="sidebar" :class="{open:mobileMenu}">
  <a href="#" class="brand" @click.prevent="go('home')"><span class="brand-icon"><Droplet :size="25" :stroke-width="2.3"/></span><span>meu<span class="brand-second">combustível<span class="brand-dot">.</span></span></span></a>
  <div class="sidebar-label">SEU DIA A DIA</div>
  <nav aria-label="Navegação principal"><button v-for="item in nav" :key="item.id" :class="['nav-item',{active:page===item.id}]" @click="go(item.id)" :aria-current="page===item.id?'page':undefined"><component :is="item.icon" :size="20"/><span>{{item.label}}</span><span v-if="item.id==='fill'" class="nav-plus">+</span></button></nav>
  <div class="sidebar-bottom"><div class="private-note"><ShieldCheck :size="22"/><div><strong>Seu histórico é só seu</strong><p>Você escolhe os preços que compartilha.</p></div></div><div class="preview-profile"><div class="avatar">MC</div><div><strong>{{isDemo?'Modo demonstração':currentUser?.name}}</strong><span v-if="isDemo">Explore o Meu Combustível</span><button v-else class="text-button" @click="logoutAccount">Sair da conta</button></div></div></div>
 </aside>
 <button v-if="mobileMenu" class="menu-backdrop" @click="mobileMenu=false" aria-label="Fechar menu"></button>
 <div class="workspace">
  <header class="topbar"><div class="breadcrumbs"><button class="mobile-menu icon-button" @click="mobileMenu=!mobileMenu" aria-label="Abrir menu"><Menu :size="22"/></button><span>Meu Combustível</span><ChevronRight :size="14"/><strong>{{nav.find(n=>n.id===page)?.label}}</strong></div><div class="location"><button v-if="installPrompt" class="text-button install-button" @click="installApp"><Download :size="16"/>Instalar app</button><MapPin :size="16"/><span>São Luís, MA</span><span class="country">BR</span></div></header>
  <div v-if="isDemo" class="demo-banner"><span class="demo-badge">PRÉVIA</span><span>Dados de exemplo. Suas alterações ficam apenas nesta sessão.</span></div>
  <div v-if="!online" class="offline-banner"><Info :size="17"/>Sem conexão. Seus campos permanecem nesta tela. Reconecte para salvar.</div>
  <main>
   <Transition name="page" mode="out-in">
   <div :key="page">
    <template v-if="page==='fill'">
     <div class="page-heading"><div><div class="eyebrow">CADA LITRO CONTA</div><h1>Novo abastecimento</h1><p>Registre os valores da bomba. A gente confere a conta.</p></div><div class="heading-tag"><ShieldCheck :size="16"/>Registro privado</div></div>
     <div v-if="!vehicles.length" class="card empty-state"><Car :size="36"/><h2>Cadastre seu primeiro veículo</h2><p>Informe a marca, o modelo e a capacidade do tanque para começar.</p><button class="primary-button" @click="newVehicle">Adicionar veículo</button></div>
     <form v-else @submit.prevent="saveFill" class="fill-layout">
      <div class="form-column">
       <section class="card form-card"><div class="section-heading"><span class="step-number">01</span><h2>Onde e com qual veículo?</h2></div><div class="field-grid"><label class="field"><span>Veículo</span><div class="input-icon"><Bike :size="19"/><select v-model="form.vehicle" @change="form.ack=false"><option v-for="v in vehicles" :value="v.id">{{v.brand}} {{v.model}} · {{v.year}}</option></select></div></label><label class="field"><span>Data do abastecimento</span><input type="date" v-model="form.date" :max="dateInput()" required/></label></div><label class="field station-field"><span>Posto de combustível <button type="button" class="text-button" @click="newStation"><Plus :size="14"/>Cadastrar posto</button></span><div class="input-icon"><MapPin :size="19"/><select v-model="form.station" @change="stationChanged"><option v-if="!stations.length" :value="0" disabled>Cadastre seu primeiro posto</option><option v-for="s in stations" :value="s.id">{{s.name}}</option></select></div><small v-if="selectedStation">{{selectedStation.address}} · {{selectedStation.city}}, {{selectedStation.state}}</small></label></section>
       <section class="card form-card"><div class="section-heading"><span class="step-number">02</span><h2>O que aparece na bomba?</h2></div><div class="field-grid fuel-fields"><label class="field"><span>Combustível</span><select v-model="form.fuel" @change="fuelChanged"><option>Gasolina comum</option><option>Gasolina aditivada</option><option>Etanol</option><option>Diesel S10</option><option>Diesel S500</option></select></label><label class="field"><span>Pagamento</span><select v-model="form.payment" @change="form.price='';form.ack=false"><option>Pix</option><option>Dinheiro</option><option>Débito</option><option>Crédito</option><option>Aplicativo / desconto</option></select></label></div>
       <div class="pump-values"><label class="field"><span>Preço por litro</span><div class="amount-input"><span>R$</span><input aria-label="Preço por litro" inputmode="decimal" v-model="form.price" placeholder="0,00" required @input="form.ack=false"/></div><small>Preço anunciado no posto</small></label><label class="field"><span>Total pago</span><div class="amount-input"><span>R$</span><input aria-label="Total pago" inputmode="decimal" v-model="form.total" placeholder="0,00" required @input="form.ack=false"/></div><small>Valor cobrado na bomba</small></label><label class="field"><span>Quantidade de litros</span><div class="amount-input"><input aria-label="Quantidade de litros" inputmode="decimal" v-model="form.liters" placeholder="0,000" required @input="form.ack=false"/><span>L</span></div><small>Volume indicado na bomba</small></label></div>
       <div v-if="calculation" :class="['calculation-status',needsCheck?'warning':'success']" aria-live="polite"><component :is="needsCheck?AlertTriangle:CheckCircle2" :size="21"/><div><strong>{{overCapacity?'Quantidade acima da capacidade cadastrada':calculation.consistent?'Tudo certo com os valores':'Vamos conferir esses valores?'}}</strong><p>{{overCapacity?`O tanque cadastrado tem ${num(selectedVehicle.capacity)} L. Revise a capacidade ou os litros.`:calculation.consistent?'O total corresponde ao preço por litro × quantidade abastecida.':`Há uma diferença de ${money(Math.abs(calculation.difference))}. Confira os números e eventuais descontos.`}}</p></div></div>
       <label v-if="needsCheck" class="check-row review-check"><input type="checkbox" v-model="form.ack"/>Conferi os dados e quero manter os valores informados.</label>
       </section>
       <section class="card form-card"><div class="section-heading"><span class="step-number">03</span><h2>Detalhes do abastecimento</h2><span class="optional">Opcional</span></div><div class="field-grid"><label class="field"><span>Quilometragem atual</span><div class="amount-input regular"><input v-model="form.km" inputmode="numeric" placeholder="Ex.: 4400"/><span>km</span></div></label><div class="tank-toggle"><div><strong>Completou o tanque?</strong><small>Ajuda a acompanhar o consumo.</small></div><button type="button" role="switch" :aria-checked="form.full" aria-label="Completou o tanque?" :class="['switch',{on:form.full}]" @click="form.full=!form.full"><span></span></button></div></div><label class="field notes-field"><span>Observação</span><textarea v-model="form.note" placeholder="Algo que você queira lembrar deste abastecimento…" rows="2" maxlength="1000"></textarea></label></section>
       <div class="share-row"><label class="check-row"><input type="checkbox" v-model="form.share"/><span><strong>Contribuir com o preço deste posto</strong><small>Compartilhe somente combustível, preço, data e condição de pagamento.</small></span></label><Globe :size="21"/></div><p v-if="error" class="form-error" role="alert">{{error}}</p><div class="form-actions"><button type="button" class="text-button muted" @click="resetForm">Limpar campos</button><button type="submit" class="primary-button" :disabled="saving||(!isDemo&&!online)"><Check :size="19"/>{{saving?'Salvando…':'Salvar abastecimento'}}</button></div>
      </div>
      <aside class="summary-column"><section class="vehicle-summary"><div class="summary-top"><span>SEU VEÍCULO</span><Bike :size="28"/></div><h2>{{selectedVehicle?.brand}} {{selectedVehicle?.model}}</h2><p>{{selectedVehicle?.type}} · {{selectedVehicle?.year}}</p><div class="tank-capacity"><span><Fuel :size="16"/>Capacidade do tanque</span><strong>{{num(selectedVehicle?.capacity??0)}} L</strong></div></section><section class="card receipt"><div class="receipt-title"><ReceiptText :size="19"/><h2>Conferência da bomba</h2></div><p class="receipt-subtitle">Uma conta simples. Mais tranquilidade.</p><div class="receipt-line"><span>Preço informado</span><strong>{{calculation?money(parseDecimal(form.price)):'—'}}<small> / L</small></strong></div><div class="receipt-line"><span>Litros abastecidos</span><strong>{{calculation?num(parseDecimal(form.liters),3)+' L':'—'}}</strong></div><div class="receipt-divider"></div><div class="receipt-line"><span>Total esperado</span><strong>{{calculation?money(calculation.expected):'—'}}</strong></div><div class="receipt-total"><span>Total pago</span><strong>{{calculation?money(parseDecimal(form.total)):'R$ —'}}</strong></div><div v-if="calculation" class="receipt-difference"><span>Diferença</span><strong :class="{negative:!calculation.consistent}">{{money(calculation.difference)}}</strong></div><div class="receipt-effective"><span>Preço efetivo por litro</span><strong>{{calculation?money(calculation.effective):'—'}}</strong></div><p class="receipt-footnote"><Info :size="15"/><span>A conferência compara os valores digitados. Não verifica a qualidade do combustível nem o volume entregue.</span></p></section><section v-if="latest" class="last-fill"><div class="last-heading"><History :size="17"/><h3>Seu último abastecimento</h3></div><p>{{displayDate(latest.date)}} · {{latest.fuel}}</p><div><strong>{{money(latest.total)}}</strong><span>{{num(latest.liters,3)}} litros</span></div><p v-if="comparison!==null" class="comparison">{{Math.abs(comparison)<0.02?'Mesmo custo por litro do último registro.':`${money(Math.abs(comparison))} ${comparison<0?'a menos':'a mais'} para a mesma quantidade de litros.`}}</p></section></aside>
     </form>
    </template>

    <template v-else-if="page==='home'">
     <div class="page-heading"><div><div class="eyebrow">SEU CAMINHO, SOB CONTROLE</div><h1>Visão geral</h1><p>Um olhar sobre seus veículos e abastecimentos.</p></div><button class="primary-button" @click="go('fill')"><Plus :size="18"/>Novo abastecimento</button></div>
     <div class="stats-grid"><section class="stat-card"><div><span>Total registrado</span><Wallet :size="20"/></div><strong>{{money(totalSpend)}}</strong><small>{{fills.length}} abastecimentos {{isDemo?'nesta demonstração':'registrados'}}</small></section><section class="stat-card"><div><span>Volume abastecido</span><Droplet :size="20"/></div><strong>{{num(totalLiters,3)}} <em>L</em></strong><small>Todos os veículos cadastrados</small></section><section class="stat-card"><div><span>Preço médio pago</span><Fuel :size="20"/></div><strong>{{money(average)}} <em>/ L</em></strong><small>Média ponderada pelo volume</small></section></div>
     <div class="overview-grid"><section class="card chart-card"><div class="section-title"><div><h2>Seus últimos abastecimentos</h2><p>Valor total por registro</p></div><span class="subtle-pill">Em reais</span></div><div v-if="!fills.length" class="empty-state"><Fuel :size="30"/><p>Seu primeiro abastecimento aparecerá aqui.</p></div><div v-else class="bar-chart"><div v-for="f in sortedFills.slice(0,7).reverse()" :key="f.id" class="chart-column"><span>{{money(f.total)}}</span><div class="chart-bar" :style="{height:Math.max(8,f.total/Math.max(...fills.map(x=>x.total))*135)+'px'}"></div><small>{{displayDate(f.date)}}</small></div></div></section><section class="recommend-card"><span class="eyebrow">EXPLORE A REGIÃO</span><MapPin :size="30"/><h2>Um bom preço pode estar no seu caminho.</h2><p>Compare os postos e encontre quem oferece calibrador gratuito.</p><button class="light-button" @click="go('stations')">Ver postos no mapa<ArrowUpRight :size="18"/></button><small>{{isDemo?'Preços fictícios nesta prévia.':'Preços compartilhados pela comunidade.'}}</small></section></div>
     <section class="card table-card"><div class="section-title"><h2>Histórico recente</h2><button class="text-button" @click="go('history')">Ver todos<ChevronRight :size="16"/></button></div><div class="table-scroll"><table><thead><tr><th>Posto / data</th><th>Veículo</th><th>Litros</th><th>Total</th><th></th></tr></thead><tbody><tr v-for="f in sortedFills.slice(0,4)" :key="f.id"><td><strong>{{stationName(f.station)}}</strong><small>{{displayDate(f.date)}} · {{f.fuel}}</small></td><td>{{vehicleName(f.vehicle)}}</td><td>{{num(f.liters,3)}} L</td><td><strong>{{money(f.total)}}</strong></td><td><button class="icon-button" @click="openFill(f)" aria-label="Ver abastecimento"><ChevronRight :size="19"/></button></td></tr></tbody></table></div></section>
    </template>

    <template v-else-if="page==='history'">
     <div class="page-heading"><div><div class="eyebrow">CADA REGISTRO, UMA HISTÓRIA</div><h1>Seus abastecimentos</h1><p>Compare valores e acompanhe cada parada.</p></div><button class="primary-button" @click="go('fill')"><Plus :size="18"/>Novo abastecimento</button></div>
     <div class="filter-bar"><div class="search-input"><Search :size="18"/><input v-model="historyQuery" placeholder="Buscar por posto, veículo ou combustível" aria-label="Buscar abastecimentos"/></div><select v-model="historyVehicle" aria-label="Filtrar veículo"><option value="all">Todos os veículos</option><option v-for="v in vehicles" :value="v.id">{{v.brand}} {{v.model}}</option></select><select v-model="historyMonth" aria-label="Filtrar mês"><option value="all">Todo o período</option><option v-for="m in historyMonths" :value="m">{{new Date(m+'-02').toLocaleDateString('pt-BR',{month:'long',year:'numeric'})}}</option></select></div>
     <section class="card table-card"><div class="section-title"><div><h2>{{filteredFills.length}} abastecimentos</h2><p>{{money(filteredFills.reduce((s,f)=>s+f.total,0))}} no período selecionado</p></div><button class="secondary-button" @click="exportHistory"><Download :size="17"/>Exportar CSV</button></div><div class="table-scroll"><table><thead><tr><th>Posto / data</th><th>Veículo</th><th>Preço / L</th><th>Litros</th><th>Total pago</th><th></th></tr></thead><tbody><tr v-for="f in filteredFills" :key="f.id"><td><strong>{{stationName(f.station)}}</strong><small>{{displayDate(f.date)}} · {{f.fuel}}</small></td><td>{{vehicleName(f.vehicle)}}</td><td>{{money(f.price)}}</td><td>{{num(f.liters,3)}} L</td><td><strong>{{money(f.total)}}</strong></td><td><button class="icon-button" @click="openFill(f)" aria-label="Ver detalhes do abastecimento"><ChevronRight :size="19"/></button></td></tr></tbody></table></div><div v-if="!filteredFills.length" class="empty-state"><Search :size="30"/><h3>Nenhum abastecimento encontrado</h3><p>Experimente outro posto, veículo ou período.</p><button class="text-button" @click="historyQuery='';historyVehicle='all';historyMonth='all'">Limpar filtros</button></div></section>
    </template>

    <template v-else-if="page==='vehicles'">
     <div class="page-heading"><div><div class="eyebrow">PRONTOS PARA O PRÓXIMO CAMINHO</div><h1>Meus veículos</h1><p>Um histórico separado para cada veículo.</p></div><button class="primary-button" @click="newVehicle"><Plus :size="18"/>Adicionar veículo</button></div>
     <div class="vehicle-grid"><section v-for="v in vehicles" :key="v.id" class="card vehicle-card"><div class="vehicle-card-top"><span class="vehicle-icon"><component :is="v.type==='Moto'?Bike:Car" :size="32"/></span><span v-if="v.primary" class="subtle-pill"><Star :size="13"/>Principal</span></div><h2>{{v.brand}} {{v.model}}</h2><p>{{v.type}} · {{v.year}}</p><div class="vehicle-specs"><div><span>Capacidade do tanque</span><strong>{{num(v.capacity)}} litros</strong></div><div><span>Combustível</span><strong>{{v.fuel}}</strong></div><div><span>Abastecimentos</span><strong>{{fills.filter(f=>f.vehicle===v.id).length}}</strong></div></div><div class="vehicle-actions"><button class="text-button" @click="editVehicle(v)">Editar veículo</button><button class="secondary-button" @click="form.vehicle=v.id;go('fill')"><Fuel :size="16"/>Abastecer</button></div></section><button class="add-vehicle-card" @click="newVehicle"><span><Plus :size="27"/></span><strong>Mais um veículo?</strong><p>Carro, moto, van e muito mais.</p></button></div>
     <div class="info-strip"><Info :size="20"/><p>A capacidade do tanque ajuda a conferir os registros. Ela não indica quanto combustível ainda resta no veículo.</p></div>
    </template>

    <template v-else-if="page==='stations'">
     <div class="page-heading"><div><div class="eyebrow">ESCOLHA SUA PRÓXIMA PARADA</div><h1>Explore os postos</h1><p>Compare preços e serviços em um só lugar.</p></div><button class="secondary-button" @click="newStation"><Plus :size="18"/>Cadastrar posto</button></div>
     <div class="filter-bar station-filters"><div class="search-input"><Search :size="18"/><input v-model="stationQuery" placeholder="Buscar posto ou bairro" aria-label="Buscar posto ou bairro"/></div><select v-model="region" aria-label="Região"><option>São Luís</option><option>Maranhão</option><option>Brasil</option></select><span class="filter-static"><Fuel :size="16"/>Gasolina comum · Pix</span><label class="filter-check"><input type="checkbox" v-model="onlyAir"/>Calibrador grátis</label></div><div class="map-demo-note"><Info :size="15"/>{{isDemo?'Os postos, preços e posições abaixo são fictícios.':'Preços informados nos últimos 7 dias. Os cadastros são feitos pelos usuários.'}} A busca automática pelo Google Maps ainda não está conectada.</div>
     <div class="explore-grid"><section class="card ranking"><div class="ranking-title"><div><h2>Ranking de preços</h2><span>{{pricedStations.length}} postos com preço informado</span></div><select v-model="sort" aria-label="Ordenar preços"><option value="cheap">Menor preço</option><option value="expensive">Maior preço</option></select></div><button v-for="(s,index) in pricedStations" :key="s.id" :class="['station-row',{selected:s.id===mapSelected}]" @click="mapSelected=s.id"><span class="rank-number">{{String(index+1).padStart(2,'0')}}</span><div class="station-description"><strong>{{s.name}}</strong><small>{{s.address}} · {{s.state}}</small><span v-if="s.air==='Gratuito'" class="air-label"><Wind :size="13"/>Calibrador grátis</span><span v-else class="station-update">Atualizado em {{displayDate(s.updated)}}</span></div><div class="station-price"><strong>{{money(s.price)}}</strong><span>por litro</span></div></button><div v-if="!pricedStations.length" class="empty-state"><MapPin :size="28"/><p>Nenhum posto com preço para estes filtros.</p></div><div class="ranking-foot"><ShieldCheck :size="15"/><span>{{isDemo?'Preços de exemplo, sem validade comercial.':'Confirme os preços no posto antes de abastecer.'}}</span></div></section><div class="map-column"><StationMap :demo="isDemo" :stations="pricedStations" :selected="mapSelected" @select="mapSelected=$event"/><section v-if="stationDetail" class="card map-detail"><div><h3>{{stationDetail.name}}</h3><p>{{stationDetail.address}} · {{stationDetail.city}}</p><div class="detail-tags"><span><Wind :size="14"/>Calibrador: {{stationDetail.air.toLowerCase()}}</span><button class="text-button" @click="openModal('report')">Relatar problema</button></div></div><button class="primary-button" @click="fillAt(stationDetail)"><Fuel :size="17"/>Abastecer aqui</button></section></div></div>
    </template>
   </div>
   </Transition>
   <footer class="app-footer"><span>Meu Combustível<span class="brand-dot">.</span></span><span>Mais clareza a cada abastecimento.</span></footer>
  </main>
 </div>
 <nav class="bottom-nav" aria-label="Navegação no celular"><button v-for="item in nav" :key="item.id" :class="{active:page===item.id}" @click="go(item.id)" :aria-current="page===item.id?'page':undefined"><component :is="item.icon" :size="21"/><span>{{item.id==='home'?'Início':item.id==='stations'?'Postos':item.id==='vehicles'?'Veículos':item.label}}</span></button></nav>
 <Transition name="toast"><div v-if="toast" class="toast" role="status"><CheckCircle2 :size="21"/><span>{{toast}}</span><button @click="toast=''" aria-label="Fechar aviso"><X :size="17"/></button></div></Transition>
 <dialog ref="modal" class="modal" @click="($event.target===modal)&&closeModal()"><div class="modal-content"><button class="modal-close icon-button" @click="closeModal" aria-label="Fechar janela"><X :size="21"/></button>
  <template v-if="modalType==='vehicle'"><div class="eyebrow">SUA GARAGEM</div><h2>{{editingId?'Editar veículo':'Adicionar veículo'}}</h2><p>{{isDemo?'Os dados ficam apenas nesta sessão de demonstração.':'Este veículo e seu histórico ficam disponíveis somente para você.'}}</p><form @submit.prevent="saveVehicle"><div class="field-grid"><label class="field"><span>Tipo</span><select v-model="vehicleDraft.type"><option>Moto</option><option>Carro</option><option>Van</option><option>Caminhonete</option><option>Caminhão</option><option>Outro</option></select></label><label class="field"><span>Ano</span><input type="number" v-model="vehicleDraft.year" min="1900" :max="new Date().getFullYear()+1" required/></label></div><label class="field"><span>Marca</span><input v-model="vehicleDraft.brand" placeholder="Ex.: Yamaha" required maxlength="80"/></label><label class="field"><span>Modelo</span><input v-model="vehicleDraft.model" placeholder="Ex.: Fluo 125" required maxlength="80"/></label><div class="field-grid"><label class="field"><span>Capacidade do tanque (L)</span><input v-model="vehicleDraft.capacity" inputmode="decimal" placeholder="Ex.: 4,2" required/></label><label class="field"><span>Combustível principal</span><select v-model="vehicleDraft.fuel"><option>Gasolina comum</option><option>Gasolina aditivada</option><option>Etanol</option><option>Flex</option><option>Diesel S10</option><option>Diesel S500</option></select></label></div><label class="check-row"><input type="checkbox" v-model="vehicleDraft.primary"/>Usar como veículo principal</label><p v-if="modalError" role="alert" class="form-error">{{modalError}}</p><button class="primary-button wide" :disabled="modalSaving"><Check :size="18"/>{{modalSaving?'Salvando…':'Salvar veículo'}}</button></form></template>
  <template v-else-if="modalType==='station'"><div class="eyebrow">CADASTRO COLABORATIVO</div><h2>Cadastrar posto</h2><p>{{isDemo?'Cadastro manual de demonstração.':'Confira os dados do estabelecimento antes de salvar.'}} A busca automática pelo Google Maps ainda não está conectada.</p><form @submit.prevent="saveStation"><label class="field"><span>Nome do posto</span><input v-model="stationDraft.name" required maxlength="120"/></label><label class="field"><span>Endereço</span><input v-model="stationDraft.address" required maxlength="200"/></label><div class="field-grid"><label class="field"><span>Cidade</span><input v-model="stationDraft.city" required/></label><label class="field"><span>Estado (UF)</span><input v-model="stationDraft.state" required maxlength="2" minlength="2"/></label></div><button type="button" class="secondary-button wide" @click="locate" :disabled="locating"><Navigation :size="17"/>{{locating?'Buscando localização…':'Usar minha localização'}}</button><div class="field-grid"><label class="field"><span>Latitude</span><input v-model="stationDraft.lat" placeholder="-2.5025" required/></label><label class="field"><span>Longitude</span><input v-model="stationDraft.lng" placeholder="-44.2896" required/></label></div><label class="field"><span>Calibrador de pneus</span><select v-model="stationDraft.air"><option>Não informado</option><option>Gratuito</option><option>Pago</option></select></label><p v-if="modalError" role="alert" class="form-error">{{modalError}}</p><button class="primary-button wide" :disabled="modalSaving"><Plus :size="18"/>{{modalSaving?'Salvando…':isDemo?'Adicionar nesta sessão':'Cadastrar posto'}}</button></form></template>
  <template v-else-if="modalType==='fillDetail'&&detailFill"><div class="eyebrow">SEU REGISTRO</div><h2>Detalhes do abastecimento</h2><p>{{stationName(detailFill.station)}}</p><div class="detail-total">{{money(detailFill.total)}}</div><dl class="detail-list"><div><dt>Data</dt><dd>{{displayDate(detailFill.date)}}</dd></div><div><dt>Veículo</dt><dd>{{vehicleName(detailFill.vehicle)}}</dd></div><div><dt>Combustível</dt><dd>{{detailFill.fuel}}</dd></div><div><dt>Preço informado</dt><dd>{{money(detailFill.price)}} / L</dd></div><div><dt>Quantidade</dt><dd>{{num(detailFill.liters,3)}} L</dd></div><div><dt>Preço efetivo</dt><dd>{{money(detailFill.total/detailFill.liters)}} / L</dd></div><div><dt>Quilometragem</dt><dd>{{detailFill.km===null?'Não informada':num(detailFill.km)+' km'}}</dd></div><div><dt>Tanque cheio</dt><dd>{{detailFill.full?'Sim':'Não'}}</dd></div><div><dt>Pagamento</dt><dd>{{detailFill.payment}}</dd></div></dl><p v-if="detailFill.note" class="note-display">{{detailFill.note}}</p><button class="secondary-button wide" @click="closeModal">Fechar</button></template>
  <template v-else-if="modalType==='report'"><div class="eyebrow">RELATO DO USUÁRIO</div><h2>Relatar um problema</h2><p>{{stationDetail?.name}}</p><div class="info-strip"><Info :size="20"/><p>Um relato não comprova adulteração. {{isDemo?'Nesta prévia, ele será apenas simulado, sem publicação.':'Seu relato passará por moderação antes de qualquer publicação.'}}</p></div><form @submit.prevent="submitReport"><label class="field"><span>O que você percebeu?</span><select v-model="reportDraft.type"><option>Falhas após abastecer</option><option>Queda de rendimento</option><option>Dificuldade para ligar</option><option>Divergência nos valores</option><option>Calibrador indisponível</option><option>Outro problema</option></select></label><label class="field"><span>Data do ocorrido</span><input type="date" v-model="reportDraft.date" :max="dateInput()" required/></label><label class="field"><span>Descreva o ocorrido</span><textarea v-model="reportDraft.description" rows="4" minlength="15" maxlength="1500" required placeholder="Conte o que aconteceu, sem incluir dados pessoais."></textarea></label><p v-if="modalError" role="alert" class="form-error">{{modalError}}</p><button class="primary-button wide" :disabled="modalSaving">{{modalSaving?'Enviando…':isDemo?'Simular envio para moderação':'Enviar para moderação'}}</button></form></template>
 </div></dialog>
 </div>
</template>
